### ISSUE TITLE
Feature request: don't depends on current working directory

### ISSUE THREAD

**Issue by xaljer** [APZelos/blamer.nvim#24] opened 2020-07-25 16:39 UTC
> If the current directory is not a git repository the blamer will be automatically disabled.
This is not suitable for the project organized using repo like Android. for example:
```
project root (open vim from here)
  |-- git repository A
  |-- git repository B
  |-- ...
```
Detecting git root from current file is more compatible.

**Comment by georgesofianosgr** [comment] 2021-03-19 06:57
Duplicate of #15

**Closed by georgesofianosgr** 2021-03-19 06:57 UTC
